In [3]:
import torch
import numpy as np
import nmmo
from nmmo import config
from neurips2022nmmo import CompetitionConfig, TeamBasedEnv
from nmmo.io import action

class TrainConfig(CompetitionConfig):
    MAP_N = 2

env = TeamBasedEnv(TrainConfig())

obs = env.reset()

obs,reward,done,info = env.step({})

100%|██████████| 2/2 [00:00<00:00, 17.27it/s]

Generating 2 maps


In [4]:
import yaml
from easydict import EasyDict

with open("./scripts/config/config.yml", 'r') as f:
    arg_file = yaml.full_load(f)
args = EasyDict(arg_file)

In [5]:
for _ in range(10):
    obs,reward,done,info = env.step({})

from utils.envParser import ObservationParser

In [6]:
obs[15][7]['Entity']['Continuous'][:int(obs[15][7]['Entity']['N'])]

array([[  1., 128.,   0.,   1.,   0.,   0.,  15.,  25.,  16.,   0.,  11.,
          0.,   1., 100.,  45.,  45.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.],
       [  1., -69.,   0.,   1.,   4.,   0.,  -1.,  21.,  17.,   0.,   8.,
          0.,   1., 100., 100., 100.,   1.,   1.,   1.,   0.,   0.,   0.,
          0.,   0.],
       [  1., -53.,   0.,   1.,   1.,   0.,  -1.,  26.,  17.,   0.,   9.,
          0.,   1., 100., 100., 100.,   1.,   1.,   1.,   0.,   0.,   0.,
          0.,   0.],
       [  1., 127.,   0.,   1.,   0.,   0.,  15.,  27.,  16.,   0.,  11.,
          0.,   1., 100.,  45.,  45.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.],
       [  1., 126.,   0.,   1.,   0.,   0.,  15.,  29.,  16.,   0.,  11.,
          0.,   1., 100.,  45.,  45.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.],
       [  1., 125.,   0.,   1.,   0.,   0.,  15.,  31.,  16.,   0.,  11.,
          0.,   1., 100.,  45.,  45.,   1.,   1.,   1.,   1.,   1.,   1.,
       

In [7]:
for i in range(5):
    x = abs(obs[15][7]['Entity']['Continuous'][i][7:9]-obs[15][7]['Entity']['Continuous'][0][7:9])
    print(x)

[0. 0.]
[4. 1.]
[1. 1.]
[2. 0.]
[4. 0.]


In [8]:
parser = ObservationParser()
entities, available, order_in_obs, group_id, global_id, cnt, tiles = parser.parse(obs[15], args)

ValueError: too many values to unpack (expected 7)

In [20]:
print(available[:cnt,7])
print(global_id[:cnt])

[0 0 0 0 0 0 0 0 0 1]
[ 120  123  122  121 -127  124  125  126  127  -78]


In [1]:
obs[0][1]['Tile']['Continuous']
# [obs[0][0]['Tile']['Continuous'][i][1] for i in [97,111,112,113,126] ]


NameError: name 'obs' is not defined

In [16]:
'''
0: i-1
1: i+1
2: j+1
3: j-1
'''
actions_by_team = {
    0: {
        0:  {
            action.Move: {
                action.Direction: 2
            },
            action.Attack:{
                action.Style: 0,
                action.Target: 1
            },
        }
    }
}

obs,_,_,_ = env.step(actions_by_team)